services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./database/store:/var/lib/mysql
    networks:
      - network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    networks:
      - network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    restart: always

    ports:
      - 80:80

    depends_on:
      - backend

    networks:
        - network

networks:
  network: